### Exercise

A. Create an ndarry object (A) with any values from 1 to 100 in a nested Python List. You can choose your range from the given values (1-100).

* Given that A is an ndarray object, many functionalities in numpy could be accessed by:
    + Make sure to explain each line of codes that you have created.

1. Using a property of the ndarray object
      - e.g. `A.shape`
2. Using a method of the ndarray object
      - e.g. `A.max()`
3. Using a numpy function and passing an ndarray
     - e.g. `np.max(A)`

B. Create a 5x5 integer-array filled with ones.
* Check its shape, size, and number of dimensions. Explain briefly the codes you have created by writing a comment beside the code.

C. Create an array of values from -5 to + 5. Multiply each value with 2. Print the resulting array.

In [1]:
import numpy as np  # This is how to import numpy and assigning as np
A = np.array([1, 2, 3, 4, 5])  # initialize an array
print(A) # print the value of A
print("Shape:", A.shape) # print the size of each dimension of an array
print("Max:", A.max()) # print total value of elements in an array
print("Max using numpy:", np.max(A)) # print total value of elements in an array by using the function of numpy

[1 2 3 4 5]
Shape: (5,)
Max: 5
Max using numpy: 5


In [2]:
B = np.ones((5, 5), dtype=int) # B has a value of an  5X5 array with a data type of an integer all filled with ones
print(B) # print value of B
print(B.shape) # print the size of each dimension in the array B
print(B.size) # print the total size of the array B
print(np.ndim(B)) # print numbers of dimension in the array B

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
(5, 5)
25
2


### Exercise

A. Choose the values from the range of numbers 1 to 100.
1. Create an array with 30 values within the range of numbers given. You can choose your own start value and stop value. However, the incrementing value will be 2.
   * Explain what is the result briefly by writing a comment before the code.
2. Multiply the resulting array with 3. Print the result.

In [3]:
import numpy as np
A1 = np.arange(10, 70, 2) # created an array with 30 values within range of numbers given with an increment of 2

#print(A1) # print the A1 with just 30 values in it
#print(A1.size) # print the total size of the array

A2 = (A1 * 3) # Multiply the resulting array by 3
print(A2) # Print the result

[ 30  36  42  48  54  60  66  72  78  84  90  96 102 108 114 120 126 132
 138 144 150 156 162 168 174 180 186 192 198 204]


### Exercise

A. Create a four-dimensional array of random integers in the interval [0, 12]. Print the result.
1. Get the dimensions, shape, and size.
    * Explain what is the result briefly by writing a comment before the code.

B. Get the maximum number for each dimensions and display it.
   * Explain what is the result briefly by writing a comment before the code.

C. Multipy each array with 4. What is its result?
    * Write a brief explanation on the multiplication process.


In [4]:
import numpy as np
array4D = np.random.randint(0, 13, size=(3, 4, 5, 6))
print(array4D) # Print the array
print(np.ndim(array4D)) # print the dimensions of the array using the function of numpy
print(array4D.shape) # print size of each dimension
print(array4D.size) # print the total size of the array

[[[[ 0  1  5  0  5  1]
   [ 7  9  4 12  2  9]
   [11  1  2  5 11  1]
   [ 4  1 12  4 10  1]
   [ 6  3  8  6  9  6]]

  [[12  0  3  9  2  3]
   [12  0  1  2  3  5]
   [ 8  5  1  1 11  5]
   [ 6  6  4  0  8  6]
   [ 8 11  8 11  0  1]]

  [[12  4  1  8 12  0]
   [ 1  6  3  9  9 11]
   [ 7 10 10  3  0  3]
   [ 1  3 10 10 12 10]
   [ 1  9  4  2  6  2]]

  [[ 7  2  8 11  8 10]
   [ 8  6 12  3 12  5]
   [ 4  2 10  3  8  6]
   [ 9 11  9 12  5  5]
   [ 3 12  4  5  4 11]]]


 [[[12 10  2  2 11  6]
   [ 4  4  4  9  9  3]
   [ 1 12  9  9  0  2]
   [ 8 11  5  9  1  4]
   [ 4 10 12  9 10  1]]

  [[11 11  4  3  6  1]
   [ 4  6  3 12  5 10]
   [ 2  9  7  2 12  9]
   [ 8  7 10  0  4 11]
   [ 8  2  3  9 12 12]]

  [[ 8 10  7  2  5  4]
   [10  1  6 12  4 12]
   [ 9  7  0  3  9  9]
   [ 0  1  8  6  3 11]
   [ 5  4  2  8  1  0]]

  [[ 9  2  3 11  4  0]
   [ 4  4  7  4 10 10]
   [ 5  0  8  7  6  2]
   [ 3  7  5 12 11  4]
   [11  7  3  1  0  4]]]


 [[[ 9  3  2  7 10 10]
   [ 8  3  7  7  8 12]
   [ 7  3  2  

In [5]:
max4D = np.max(array4D, axis=(0, 1, 2, 3)) # Using the function of numpy to get the maximum number for each dimensions
print(max4D) # Print the maximum number for each dimension

12


In [6]:
multiply4D = array4D * 4 # Multipy each array with 4
print(multiply4D) # Each element in the array4D is multiplied by 4, resulting in a new array where all values are four times larger than the original values.

[[[[ 0  4 20  0 20  4]
   [28 36 16 48  8 36]
   [44  4  8 20 44  4]
   [16  4 48 16 40  4]
   [24 12 32 24 36 24]]

  [[48  0 12 36  8 12]
   [48  0  4  8 12 20]
   [32 20  4  4 44 20]
   [24 24 16  0 32 24]
   [32 44 32 44  0  4]]

  [[48 16  4 32 48  0]
   [ 4 24 12 36 36 44]
   [28 40 40 12  0 12]
   [ 4 12 40 40 48 40]
   [ 4 36 16  8 24  8]]

  [[28  8 32 44 32 40]
   [32 24 48 12 48 20]
   [16  8 40 12 32 24]
   [36 44 36 48 20 20]
   [12 48 16 20 16 44]]]


 [[[48 40  8  8 44 24]
   [16 16 16 36 36 12]
   [ 4 48 36 36  0  8]
   [32 44 20 36  4 16]
   [16 40 48 36 40  4]]

  [[44 44 16 12 24  4]
   [16 24 12 48 20 40]
   [ 8 36 28  8 48 36]
   [32 28 40  0 16 44]
   [32  8 12 36 48 48]]

  [[32 40 28  8 20 16]
   [40  4 24 48 16 48]
   [36 28  0 12 36 36]
   [ 0  4 32 24 12 44]
   [20 16  8 32  4  0]]

  [[36  8 12 44 16  0]
   [16 16 28 16 40 40]
   [20  0 32 28 24  8]
   [12 28 20 48 44 16]
   [44 28 12  4  0 16]]]


 [[[36 12  8 28 40 40]
   [32 12 28 28 32 48]
   [28 12  8 2